# Generated by Django 4.2.6 on 2023-10-13 14:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_created=True)),
                ('serial', models.CharField(max_length=4, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('router', models.CharField(max_length=15)),
                ('service_plan', models.CharField(choices=[('PPOE', 'Ppoe'), ('STATIC', 'Static'), ('HOTSPOT', 'Hotspot')], max_length=7)),
            ],
        ),
    ]
