# Generated by Django 4.2.6 on 2023-11-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldwork",
            name="isclosed",
            field=models.BooleanField(default=True),
        ),
    ]
