# Generated by Django 4.2.6 on 2023-10-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='serial',
            field=models.CharField(blank=True, max_length=4, unique=True),
        ),
    ]
