# Generated by Django 4.2.6 on 2024-07-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_rename_provider_information_employee_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("opening_stock", models.PositiveIntegerField()),
                ("additional_stock", models.PositiveIntegerField()),
                ("out_stock", models.PositiveIntegerField()),
                ("opening_stock_date", models.DateTimeField(auto_now=True)),
                ("restocking_date", models.DateTimeField(auto_now_add=True)),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.provider",
                    ),
                ),
            ],
        ),
    ]
