# Generated by Django 4.2.6 on 2024-06-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_client_is_paid_smsgatewayresponse_sms_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="logo",
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identification_number", models.CharField(max_length=128)),
                ("job_title", models.CharField(max_length=128)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.staff"
                    ),
                ),
            ],
        ),
    ]
