# Generated by Django 4.2.6 on 2023-12-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_provider_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mpesatransaction",
            name="bill_ref_number",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="mpesatransaction",
            name="first_name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mpesatransaction",
            name="last_name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mpesatransaction",
            name="middle_name",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="mpesatransaction",
            name="phone_number",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
