# Generated by Django 4.2.6 on 2023-10-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_client_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
