# Generated by Django 4.2.6 on 2024-07-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="additional_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="opening_stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="out_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
