# Generated by Django 4.2.6 on 2024-07-19 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_inventory_additional_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="name",
        ),
        migrations.AddField(
            model_name="material",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.inventory",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="staff",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.employee",
            ),
        ),
    ]
