# Generated by Django 4.2.6 on 2023-11-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_client_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('activities', models.TextField()),
                ('assignee', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
