# Generated by Django 4.2.6 on 2023-12-20 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_mpesatransaction_bill_ref_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesatransaction",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="accounts.client",
            ),
        ),
        migrations.AlterField(
            model_name="mpesatransaction",
            name="provider",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.provider",
            ),
        ),
    ]
