# Generated by Django 4.2.6 on 2024-07-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_material_fieldwork"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="usage_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
