# Generated by Django 4.2.6 on 2023-12-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_provider_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortmessage",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
