# Generated by Django 4.2.6 on 2023-12-26 14:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_shortmessage_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortmessage",
            name="schedule_time",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 26, 14, 38, 5, 10712, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
