# Generated by Django 4.2.6 on 2024-01-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_shortmessage_schedule_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="bandwidth",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="serial",
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
