# Generated by Django 4.2.6 on 2024-01-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_bandwidth_timestamp_alter_client_serial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandwidth",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
