# Generated by Django 4.2.6 on 2024-01-08 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0011_alter_bandwidth_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandwidth",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.provider",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.provider",
            ),
        ),
        migrations.AlterField(
            model_name="fieldwork",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.provider",
            ),
        ),
        migrations.AlterField(
            model_name="mpesatransaction",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="accounts.provider",
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shortmessage",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.provider",
            ),
        ),
    ]
