# Generated by Django 4.2.6 on 2024-01-08 15:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_bandwidth_provider_alter_client_provider_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bandwidth",
            name="expiry",
        ),
    ]
