# Generated by Django 4.2.6 on 2024-01-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_remove_bandwidth_expiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldwork",
            name="isclosed",
            field=models.BooleanField(default=False),
        ),
    ]
