# Generated by Django 4.2.6 on 2024-01-20 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="ticket",
        ),
        migrations.AlterField(
            model_name="fieldwork",
            name="assignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="worker",
                to="accounts.staff",
            ),
        ),
    ]
