# Generated by Django 4.2.6 on 2024-01-21 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_remove_fieldwork_material_meterial_material"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Meterial",
            new_name="Material",
        ),
        migrations.AlterField(
            model_name="material",
            name="material",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.fieldwork",
            ),
        ),
    ]
