# Generated by Django 4.2.6 on 2024-01-21 07:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_rename_meterial_material_alter_material_material"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="material",
            new_name="fieldwork",
        ),
    ]
