# Generated by Django 4.2.6 on 2024-01-25 12:44

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_rename_material_material_fieldwork"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This email has already been registered."},
                max_length=254,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, unique=True
            ),
        ),
    ]
