# Generated by Django 4.2.6 on 2024-02-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0021_alter_client_email_alter_client_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="service_plan",
            field=models.CharField(
                choices=[
                    ("ppoe", "Ppoe"),
                    ("static", "Static"),
                    ("hotspot", "Hotspot"),
                ],
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")], max_length=8
            ),
        ),
    ]
