# Generated by Django 4.2.6 on 2024-02-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_alter_client_service_plan_alter_client_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsGatewayResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver", models.CharField(max_length=12)),
                ("message_id", models.CharField(max_length=40)),
                ("status", models.CharField(max_length=7)),
                ("status_code", models.CharField(max_length=3)),
            ],
        ),
    ]
